### ISSUE TITLE
Does not compile - gives following error - flutter version 2+

### ISSUE THREAD

**Issue by SampathNarayanan** [chenasraf/wheel_spinner#1]
wheel_spinner-0.7.0/lib/wheel_spinner.dart:136:72: Error: The argument type 'BorderRadiusGeometry?' can't be assigned to the parameter type 'BorderRadius?'.
 - 'BorderRadiusGeometry' is from 'package:flutter/src/painting/border_radius.dart' ('/C:/flutter/packages/flutter/lib/src/painting/border_radius.dart').
 - 'BorderRadius' is from 'package:flutter/src/painting/border_radius.dart' ('/C:/flutter/packages/flutter/lib/src/painting/border_radius.dart').
                      borderRadius: _theme.boxDecoration?.borderRadius ??

**Comment by chenasraf** [comment]
Thank you for the report!
 Flutter v3 apparently changed the `ClipRRect` widget's arguments.
Version 0.7.1 (b0274c366abb27808936dbd407a02b543d5d44eb) should be fixed.
If the problem persists, please re-open this issue.
